version: '2'
services:
  hotspot_mongo:
    image: mongo
    container_name: hotspot_mongo
    hostname: hotspot_mongo
    ports:
      - 27017
    volumes:
      - ${COMPOSEROOT}/geohotspot_data:/data/db
    command: mongod --directoryperdb   
    
    
  hotspot:
    depends_on:
      - hotspot_mongo
    image: ewnchui/geohotspot
    container_name: hotspot 
    hostname: hotspot
    ports:
      - 8025:1337
      - 8026:8080
    entrypoint: top -b -d 1000
    volumes:
      #- ${COMPOSEROOT}/geohotspot/config/env/development.coffee:/usr/src/app/config/env/development.coffee
      #- ${COMPOSEROOT}/geohotspot/www/js/config/development.coffee:/usr/src/app/www/js/config/development.coffee
      - /etc/ssl/certs:/etc/ssl/certs
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates
      #- ${COMPOSEROOT}/geohotspot/entrypoint.sh:/usr/src/app/entrypoint.sh
      - ${COMPOSEROOT}/geohotspot:/usr/src/app